[tool.poetry]
name = "main"
version = "0.1.0"
description = ""
authors = ["Alexander Petrovskiy <petrovskiy.alexander@gmail.com>"]
readme = "README.md"
packages = [{include = "main", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
structlog = "^24.2.0"


[tool.poetry.group.test.dependencies]
pytest = {version = "^8.2.2", allow-prereleases = true}
allure-pytest = {version = "^2.13.5", allow-prereleases = true}
pytest-xdist = {version = "^3.6.1", allow-prereleases = true}
typing-extensions = {version = "^4.12.2", allow-prereleases = true}
pytest-test-groups = {version = "^1.0.3", allow-prereleases = true}
python-dotenv = {version = "^1.0.1", allow-prereleases = true}
pyhamcrest = {version = "^2.1.0", allow-prereleases = true}
parameterized = {version = "^0.9.0", allow-prereleases = true}


[tool.poetry.group.dev.dependencies]
pycodestyle = {version = "^2.12.0", allow-prereleases = true}
pylint = {version = "^3.2.4", allow-prereleases = true}
pyflakes = {version = "^3.2.0", allow-prereleases = true}
flake8 = {version = "^7.1.0", allow-prereleases = true}
yapf = {version = "^0.40.2", allow-prereleases = true}
autopep8 = {version = "^2.3.1", allow-prereleases = true}
black = {version = "^24.4.2", allow-prereleases = true}
autoformat = {version = "^1.0.0", allow-prereleases = true}
autoflake = {version = "^2.3.1", allow-prereleases = true}
isort = "^5.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
