name: 'DemoJSAction'
description: 'Display massage'
inputs:
  name-of-you: 'aabbcc'
  description: 'Your name'
  required: true
  default: 'Chaminda'
outputs:
  time: 'ddeeff'
  description: 'The time of the message'
runs:
  using: 'node12'
  main: 'index.js'